apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-connect
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mysql-connect
  template:
    metadata:
      labels:
        app: mysql-connect
    spec:
      containers:
      - image: python/mysql_connect:7
        name: mysql-connect
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
