apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-connect
spec:
  template:
    metadata:
      name: mysql-connect
    spec:
      containers:
      - name: mysql-connect
        image: python/mysql_connect:14
        command:
         - "python"
         - "connect_mysql.py"
      restartPolicy: Never

